export const coachNav = [
  { label: 'Command center', href: '/coach/home' },
  { label: 'Client dossiers', href: '/coach/clients' },
  { label: 'Recovery', href: '/coach/recovery' },
  { label: 'Intelligence', href: '/coach/intelligence' },
  { label: 'Risk signals', href: '/coach/risk-signals' },
  { label: 'Workouts', href: '/coach/workouts' },
  { label: 'Programs', href: '/coach/programs' },
  { label: 'Tasks', href: '/coach/tasks' },
  { label: 'Progress', href: '/coach/progress' },
  { label: 'Nutrition', href: '/coach/nutrition' },
  { label: 'Feed', href: '/coach/feed' },
  { label: 'Packages', href: '/coach/packages' },
  { label: 'Client health', href: '/coach/client-health' },
  { label: 'Messages', href: '/dashboard/messages' },
];
