import {Router} from 'express'; import {z} from 'zod'; import {prisma} from '../../lib/prisma'; import {requireAuth,AuthenticatedRequest} from '../../common/middleware/auth'; import {asyncHandler} from '../../common/utils/async-handler'; import {getClientSegment,getMomentum,getCoachNudges,getPostAnalytics,detectMilestones} from './feed.service'; export const feedRouter=Router(); feedRouter.use(requireAuth);
async function enrich(posts:any[],userId:string,clientId?:string){const ids=[...new Set(posts.map(p=>p.authorUserId))];const users=await prisma.user.findMany({where:{id:{in:ids}},select:{id:true,firstName:true,lastName:true}});const um=Object.fromEntries(users.map(u=>[u.id,u]));const pids=posts.map(p=>p.id);const rr=await prisma.feedReaction.findMany({where:{postId:{in:pids},userId}});const ss=await prisma.feedSave.findMany({where:{postId:{in:pids},userId}});const rs=new Set(rr.map(r=>r.postId));const sv=new Set(ss.map(s=>s.postId));return posts.map(p=>({...p,author:um[p.authorUserId]||null,currentUserReacted:rs.has(p.id),currentUserSaved:sv.has(p.id),primaryAction:getActionForPost(p,userId)}))}
feedRouter.get('/program/:programId',asyncHandler(async(req:AuthenticatedRequest,res)=>{const clientId=(req.query.clientId as string)||req.user!.sub;const typeFilter=req.query.type as string|undefined;const where:any={scopeType:'PROGRAM',scopeId:req.params.programId,status:'ACTIVE'};if(typeFilter)where.type=typeFilter;const posts=await prisma.feedPost.findMany({where,include:{media:true,_count:{select:{comments:true,reactions:true,saves:true}}},orderBy:[{pinnedAt:'desc'},{createdAt:'desc'}],take:50});const enriched=await enrich(posts,req.user!.sub);if(clientId&&clientId!==req.user!.sub){const seg=await getClientSegment(clientId);const order:{[key:string]:number}={ON_TRACK:0,SLIPPING:1,AT_RISK:2};enriched.sort((a:any,b:any)=>{const aP=order[getSegment(a)]??1;const bP=order[getSegment(b)]??1;return aP-bP})}res.json({items:enriched})}));
feedRouter.get('/posts/:postId/comments',asyncHandler(async(req:AuthenticatedRequest,res)=>{const comments=await prisma.feedComment.findMany({where:{postId:req.params.postId,status:'ACTIVE'},orderBy:{createdAt:'asc'}});const ids=[...new Set(comments.map(c=>c.authorUserId))];const users=await prisma.user.findMany({where:{id:{in:ids}},select:{id:true,firstName:true,lastName:true}});const um=Object.fromEntries(users.map(u=>[u.id,u]));res.json({items:comments.map(c=>({...c,author:um[c.authorUserId]||null}))})}));
feedRouter.get('/posts/:postId',asyncHandler(async(req:AuthenticatedRequest,res)=>{const post=await prisma.feedPost.findUnique({where:{id:req.params.postId},include:{media:true,_count:{select:{comments:true,reactions:true,saves:true}}}});if(!post){res.status(404).json({error:'Post not found'});return}const[enr]=await enrich([post],req.user!.sub);res.json(enr)}));
feedRouter.post('/posts',asyncHandler(async(req:AuthenticatedRequest,res)=>{const b=z.object({scopeType:z.enum(['PROGRAM','COACH_PRIVATE','CHALLENGE']),scopeId:z.string(),type:z.enum(['COACH_MESSAGE','MILESTONE','CHECK_IN_PROMPT','RECOVERY_ALERT','WORKOUT_ASSIGNED','CHALLENGE_UPDATE','NUTRITION_HACK','PROGRESS_SPOTLIGHT']).optional(),bodyText:z.string().optional(),tag:z.string().optional(),media:z.array(z.any()).default([])}).parse(req.body);res.status(201).json(await prisma.feedPost.create({data:{authorUserId:req.user!.sub,scopeType:b.scopeType,scopeId:b.scopeId,type:b.type??'COACH_MESSAGE',bodyText:b.bodyText,tag:b.tag,media:{create:b.media.map((m:any)=>({...m,ownerUserId:req.user!.sub}))}},include:{media:true}}))}));
feedRouter.patch('/posts/:postId',asyncHandler(async(req:AuthenticatedRequest,res)=>{const p=await prisma.feedPost.findUnique({where:{id:req.params.postId}});if(!p||p.authorUserId!==req.user!.sub){res.status(403).json({error:'Not authorized'});return}const b=z.object({bodyText:z.string().optional(),tag:z.string().optional(),status:z.string().optional()}).parse(req.body);res.json(await prisma.feedPost.update({where:{id:req.params.postId},data:b,include:{media:true,_count:{select:{comments:true,reactions:true,saves:true}}}}))}));
feedRouter.delete('/posts/:postId',asyncHandler(async(req:AuthenticatedRequest,res)=>{const p=await prisma.feedPost.findUnique({where:{id:req.params.postId}});if(!p||p.authorUserId!==req.user!.sub){res.status(403).json({error:'Not authorized'});return}await prisma.feedPost.delete({where:{id:req.params.postId}});res.json({success:true})}));
feedRouter.post('/posts/:postId/comments',asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.feedComment.create({data:{postId:req.params.postId,authorUserId:req.user!.sub,bodyText:req.body.bodyText}}))));
feedRouter.post('/posts/:postId/reactions',asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.feedReaction.upsert({where:{postId_userId:{postId:req.params.postId,userId:req.user!.sub}},update:{reactionType:req.body.reactionType||'LIKE'},create:{postId:req.params.postId,userId:req.user!.sub,reactionType:req.body.reactionType||'LIKE'}}))));
feedRouter.delete('/posts/:postId/reactions',asyncHandler(async(req:AuthenticatedRequest,res)=>{await prisma.feedReaction.deleteMany({where:{postId:req.params.postId,userId:req.user!.sub}});res.json({success:true})}));
feedRouter.post('/posts/:postId/saves',asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.feedSave.upsert({where:{postId_userId:{postId:req.params.postId,userId:req.user!.sub}},update:{},create:{postId:req.params.postId,userId:req.user!.sub}}))));
feedRouter.delete('/posts/:postId/saves',asyncHandler(async(req:AuthenticatedRequest,res)=>{await prisma.feedSave.deleteMany({where:{postId:req.params.postId,userId:req.user!.sub}});res.json({success:true})}));
feedRouter.post('/reports',asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.contentReport.create({data:{reporterUserId:req.user!.sub,...req.body,status:'OPEN'}}))));
feedRouter.get('/momentum',asyncHandler(async(req:AuthenticatedRequest,res)=>{res.json(await getMomentum(req.user!.sub))}));
feedRouter.get('/nudges',asyncHandler(async(req:AuthenticatedRequest,res)=>{res.json({items:await getCoachNudges(req.user!.sub)})}));
feedRouter.get('/posts/:postId/analytics',asyncHandler(async(req:AuthenticatedRequest,res)=>{const post=await prisma.feedPost.findUnique({where:{id:req.params.postId}});if(!post){res.status(404).json({error:'Not found'});return}res.json(await getPostAnalytics(req.params.postId,post.scopeId));}))

function getSegment(a:any):string{return a.type==='COACH_MESSAGE'?'ON_TRACK':'ON_TRACK'}
function getActionForPost(p:any,userId:string){if(p.type==='WORKOUT_ASSIGNED')return{type:'START_WORKOUT',label:'Start workout',href:`/client/workouts`};if(p.type==='CHECK_IN_PROMPT')return{type:'CHECK_IN',label:'Check in',apiEndpoint:'/api/checkins'};if(p.type==='MILESTONE')return{type:'VIEW_STREAK',label:'See my progress',href:'/client/progress'};if(p.type==='RECOVERY_ALERT')return{type:'LOG_RECOVERY',label:'Log how I feel',apiEndpoint:'/api/recovery/log'};if(p.type==='CHALLENGE_UPDATE')return{type:'VIEW_LEADERBOARD',label:'See leaderboard',href:'/client/progress'};if(p.type==='NUTRITION_HACK')return{type:'LOG_MEAL',label:'Log a meal',apiEndpoint:'/api/nutrition/meals'};if(p.type==='PROGRESS_SPOTLIGHT')return{type:'COMPARE_PHOTO',label:'View comparison',href:'/client/progress'};return null}
