
import {Router} from 'express'; import {prisma} from '../../lib/prisma'; import {requireAuth,AuthenticatedRequest,requireRole} from '../../common/middleware/auth'; import {asyncHandler} from '../../common/utils/async-handler';
export const paymentsRouter=Router(); export const stripeWebhookRouter=Router(); paymentsRouter.use(requireAuth);
stripeWebhookRouter.post('/',asyncHandler(async(_req,res)=>res.json({received:true,note:'Stripe webhook placeholder; configure provider for live payments'})));
paymentsRouter.post('/packages',requireRole(['coach','assistant_coach']),asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.coachingPackage.create({data:{coachUserId:req.user!.sub,title:req.body.title||req.body.name,description:req.body.description,priceCents:req.body.priceCents,currency:req.body.currency,billingType:req.body.billingType,interval:req.body.interval,trialDays:req.body.trialDays,includesJson:req.body.includesJson,isActive:req.body.isActive}}))));
paymentsRouter.get('/packages',asyncHandler(async(req,res)=>res.json({items:await prisma.coachingPackage.findMany({where:{coachUserId:req.query.coachUserId as string|undefined,isActive:true}})})));
paymentsRouter.post('/checkout',requireRole(['client']),asyncHandler(async(req:AuthenticatedRequest,res)=>{const pkg=await prisma.coachingPackage.findUnique({where:{id:req.body.packageId}}); if(!pkg) return void res.status(404).json({error:'Package not found'}); const s=await prisma.checkoutSession.create({data:{clientUserId:req.user!.sub,coachUserId:pkg.coachUserId,packageId:pkg.id,amountCents:pkg.priceCents,currency:pkg.currency,billingType:pkg.billingType,status:'CREATED'}}); return res.status(201).json({checkoutSession:s,checkoutUrl:`/checkout/mock?session=${s.id}`});}));
paymentsRouter.get('/subscriptions',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({items:await prisma.subscription.findMany({where:{clientUserId:(req.query.clientUserId as string)||req.user!.sub},include:{package:true}})})));
paymentsRouter.get('/payments',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({items:await prisma.payment.findMany({where:{clientUserId:(req.query.clientUserId as string)||req.user!.sub},include:{package:true}})})));
