
import {Router} from 'express'; import {prisma} from '../../lib/prisma'; import {requireAuth,AuthenticatedRequest,requireRole} from '../../common/middleware/auth'; import {asyncHandler} from '../../common/utils/async-handler'; import {getMetricInfo} from './constants/metric-types';
export const progressRouter=Router(); progressRouter.use(requireAuth);
progressRouter.post('/photos',asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.progressPhoto.create({data:{clientUserId:req.body.clientUserId||req.user!.sub,...req.body}}))));
progressRouter.get('/photos',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({items:await prisma.progressPhoto.findMany({where:{clientUserId:(req.query.clientUserId as string)||req.user!.sub},include:{coachNotes:true},orderBy:{capturedAt:'desc'}})})));
progressRouter.get('/photos/compare',asyncHandler(async(req,res)=>{const before=await prisma.progressPhoto.findUnique({where:{id:req.query.beforePhotoId as string}}); const after=await prisma.progressPhoto.findUnique({where:{id:req.query.afterPhotoId as string}}); res.json({before,after});}));
progressRouter.post('/metrics',asyncHandler(async(req:AuthenticatedRequest,res)=>{const metricDate=req.body.recordedAt||req.body.date; res.status(201).json(await prisma.metricEntry.create({data:{clientUserId:req.body.clientUserId||req.user!.sub,metricType:req.body.metricType,unit:req.body.unit,value:req.body.value,recordedAt:metricDate?new Date(metricDate):undefined,source:req.body.source}}));}));
progressRouter.get('/metrics',asyncHandler(async(req:AuthenticatedRequest,res)=>{const where:any={clientUserId:(req.query.clientUserId as string)||req.user!.sub}; if(req.query.metricType)where.metricType=req.query.metricType; if(req.query.from||req.query.to){const recordedAt:any={}; if(req.query.from)recordedAt.gte=new Date(req.query.from as string); if(req.query.to)recordedAt.lte=new Date(req.query.to as string); where.recordedAt=recordedAt;} const take=req.query.limit?parseInt(req.query.limit as string):undefined; res.json({items:await prisma.metricEntry.findMany({where,orderBy:{recordedAt:'desc'},take})});}));
progressRouter.get('/metrics/summary',asyncHandler(async(req:AuthenticatedRequest,res)=>{const clientUserId=(req.query.clientUserId as string)||req.user!.sub; const entries=await prisma.metricEntry.findMany({where:{clientUserId},orderBy:{recordedAt:'desc'}}); const grouped:Record<string,{values:{value:number;recordedAt:Date}[]}>={}; for(const e of entries){if(!grouped[e.metricType])grouped[e.metricType]={values:[]}; grouped[e.metricType].values.push({value:e.value,recordedAt:e.recordedAt});} const info=getMetricInfo; const items=Object.entries(grouped).map(([metricType,g])=>{const sorted=g.values.sort((a,b)=>a.recordedAt.getTime()-b.recordedAt.getTime()); const latest=sorted[sorted.length-1]; const previous=sorted.length>1?sorted[sorted.length-2]:null; const changePercent=previous&&previous.value!==0?((latest.value-previous.value)/Math.abs(previous.value)*100):0; const m=getMetricInfo(metricType); return{metricType,label:m.label,unit:m.defaultUnit||'',latestValue:latest.value,previousValue:previous?.value??null,changePercent:Math.round(changePercent*10)/10,count:sorted.length,category:m.category};}); res.json({items});}));
progressRouter.post('/checkin-forms',requireRole(['coach','assistant_coach']),asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.checkinForm.create({data:{coachUserId:req.user!.sub,...req.body}}))));
progressRouter.post('/checkins',requireRole(['client']),asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.checkinSubmission.create({data:{clientUserId:req.user!.sub,...req.body}}))));
progressRouter.get('/checkins',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({items:await prisma.checkinSubmission.findMany({where:{clientUserId:(req.query.clientUserId as string)||req.user!.sub},include:{form:true,coachNotes:true}})})));
