
import {Router} from 'express'; import {prisma} from '../../lib/prisma'; import {requireAuth,AuthenticatedRequest,requireRole} from '../../common/middleware/auth'; import {asyncHandler} from '../../common/utils/async-handler';
export const nutritionRouter=Router(); nutritionRouter.use(requireAuth);
nutritionRouter.post('/plans',requireRole(['coach','assistant_coach']),asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.nutritionPlan.create({data:{coachUserId:req.user!.sub,...req.body},include:{days:{include:{meals:true}}}}))));
nutritionRouter.get('/plans',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({items:await prisma.nutritionPlan.findMany({where:{clientUserId:(req.query.clientUserId as string)||req.user!.sub},include:{days:{include:{meals:true}}}})})));
nutritionRouter.post('/macro-goals',asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.macroGoal.create({data:{clientUserId:req.body.clientUserId||req.user!.sub,...req.body}}))));
nutritionRouter.post('/meal-logs',requireRole(['client']),asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.mealLog.create({data:{clientUserId:req.user!.sub,...req.body}}))));
nutritionRouter.get('/meal-logs',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({items:await prisma.mealLog.findMany({where:{clientUserId:(req.query.clientUserId as string)||req.user!.sub},include:{coachNotes:true}})})));
nutritionRouter.post('/recipes',requireRole(['coach','assistant_coach']),asyncHandler(async(req:AuthenticatedRequest,res)=>res.status(201).json(await prisma.recipe.create({data:{coachUserId:req.user!.sub,...req.body},include:{ingredients:true}}))));
nutritionRouter.get('/recipes',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({items:await prisma.recipe.findMany({where:{coachUserId:req.user!.sub},include:{ingredients:true}})})));
for(const path of ['hydration','sleep','steps']) nutritionRouter.post('/'+path,requireRole(['client']),asyncHandler(async(req:AuthenticatedRequest,res)=>{const model:any={hydration:prisma.hydrationLog,sleep:prisma.sleepLog,steps:prisma.stepsLog}[path]; res.status(201).json(await model.create({data:{clientUserId:req.user!.sub,...req.body}}));}));
